DROP SCHEMA IF EXISTS HIBERNATESTATS;
CREATE SCHEMA HIBERNATESTATS DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

USE HIBERNATESTATS;

DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRSTNAME VARCHAR(30),
    LASTNAME VARCHAR(30),
    TELEPHONE VARCHAR(15),
    EMAIL VARCHAR(30),
    CREATED TIMESTAMP DEFAULT NOW()
) ENGINE=InnoDB CHARACTER SET=utf8, COLLATE=utf8_general_ci;